version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    commit-message:
      prefix: '⬆️ '
    allow:
      - dependency-name: '*'
        dependency-type: 'production'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
        commit-message:
          prefix: '⬆️ [MAJOR-VERSION]'
    #https://stackoverflow.com/questions/60201543/dependabot-only-updates-lock-file
    versioning-strategy: increase
